#!/bin/bash

[ $# -ne 2 ] && echo "Usage: $0 path host:/path" && exit 1

SELF=$$
HOST=`echo $2 | cut -f1 -d:`
DEST=`echo $2 | cut -f2 -d:`
DEST=${DEST:-/tmp/}
DEST=`echo $DEST/ | sed -e 's#//#/#g'`

if ! ping -t 3 -c 1 "$HOST" >/dev/null 2>&1 ; then
 echo "Error: second argument needs to be host:/path" && exit 2
fi

if [ -f $1 ] ; then
  cd `dirname $1`
  CMD="echo `basename $1`"
elif [ -d $1 ] ; then
  cd $1
  CMD="find ."
  DEST=$DEST/`basename $1`/
else
  echo "Error: first argument needs to be either a file name or a directory" ; exit 3
fi

(for i in 1 2 3 4 5 6 7 8 9 10 ; do 
   ($CMD | cpio -o --format newc | nc $HOST 10000) && exit
   kill -0 $SELF >/dev/null 2>&1 || exit
   sleep 1
 done) &

ssh -o StrictHostKeyChecking=no -o GlobalKnownHostsFile=/dev/null -o UserKnownHostsFile=/dev/null \
     admin@$HOST run /tools/cpiod.so --prefix=$DEST
